"use strict";

const RC_DAILY_FIVE=[
 {id:"d01",icon:"🌐",domain:"Réseau",title:"Le paquet perdu",
  quiz:{q:"Ton PC atteint 1.1.1.1 mais pas example.com. Quel réflexe vient en premier ?",choices:["Vérifier DNS","Réinstaller le navigateur","Changer l’adresse MAC"],answer:0,explain:"La connectivité IP fonctionne déjà. Le symptôme oriente d’abord vers la résolution de noms."},
  mission:{prompt:"En 20 secondes, explique la différence entre une adresse IP et un nom DNS.",reveal:"IP = adresse utilisée pour joindre une machine. DNS = mécanisme qui traduit un nom lisible en adresse utilisable."},
  english:{term:"resolver",q:"Dans ce contexte, “DNS resolver” signifie…",choices:["résolveur DNS","routeur par défaut","pare-feu"],answer:0,explain:"A resolver is the component that performs DNS resolution on behalf of a client."}},
 {id:"d02",icon:"🐧",domain:"Linux",title:"Permission impossible",
  quiz:{q:"Un fichier contient rw-------. Qui peut le lire ?",choices:["Tout le monde","Le propriétaire uniquement","Le groupe uniquement"],answer:1,explain:"rw------- donne lecture + écriture au propriétaire, aucun droit au groupe ni aux autres."},
  mission:{prompt:"Explique pourquoi chmod 777 n’est pas une bonne solution par défaut.",reveal:"777 accorde lecture, écriture et exécution à tout le monde. Le bon réflexe est d’accorder uniquement les droits réellement nécessaires."},
  english:{term:"least privilege",q:"“Principle of least privilege” veut dire…",choices:["donner le minimum de droits nécessaires","supprimer tous les comptes","utiliser uniquement root"],answer:0,explain:"Least privilege means granting only the permissions required to perform a task."}},
 {id:"d03",icon:"🔐",domain:"Cyber",title:"AuthN ou AuthZ ?",
  quiz:{q:"Un utilisateur est connecté mais ne doit pas supprimer les données d’un autre. Quel contrôle décide ?",choices:["Authentification","Autorisation","Compression"],answer:1,explain:"L’authentification vérifie qui tu es ; l’autorisation vérifie ce que tu as le droit de faire."},
  mission:{prompt:"Donne un exemple simple d’authentification puis d’autorisation.",reveal:"Exemple : mot de passe + MFA pour s’authentifier ; rôle administrateur requis pour supprimer un compte."},
  english:{term:"authorization",q:"“You are authenticated but not authorized” signifie…",choices:["ton identité est vérifiée mais l’action est interdite","ton mot de passe est faux","le serveur DNS est hors ligne"],answer:0,explain:"Authenticated = identity verified. Authorized = allowed to perform the requested action."}},
 {id:"d04",icon:"🧱",domain:"Programmation",title:"La fonction mystère",
  quiz:{q:"À quoi sert principalement return dans une fonction ?",choices:["À produire une valeur pour l’appelant","À redémarrer le programme","À créer une variable globale"],answer:0,explain:"return termine l’exécution de la fonction et transmet une valeur à son appelant."},
  mission:{prompt:"Imagine une fonction tyreRisk(temp, rain). Cite ses entrées et sa sortie.",reveal:"Entrées : température et pluie. Sortie : par exemple un niveau de risque déterministe comme LOW / MEDIUM / HIGH."},
  english:{term:"return value",q:"“Return value” se traduit le mieux par…",choices:["valeur de retour","boucle infinie","nom de variable"],answer:0,explain:"A return value is the result produced by a function."}},
 {id:"d05",icon:"🚦",domain:"Git",title:"SHA sous contrôle",
  quiz:{q:"Pourquoi vérifier le SHA avant de fusionner une PR déjà revue ?",choices:["Pour confirmer que le code revu est toujours exactement celui qu’on fusionne","Pour accélérer le Wi‑Fi","Pour renommer la branche"],answer:0,explain:"Un nouveau commit change le contenu. L’approbation doit porter sur le SHA réellement fusionné."},
  mission:{prompt:"Résume en une phrase : branche → PR → CI → merge.",reveal:"On isole le changement sur une branche, on le fait relire dans une PR, la CI le valide, puis on fusionne le SHA approuvé."},
  english:{term:"reviewed commit",q:"“The reviewed commit changed” implique quoi ?",choices:["Une nouvelle vérification","Aucune conséquence","Supprimer Git"],answer:0,explain:"If the reviewed commit changes, the new SHA should be reviewed and tested again."}},
 {id:"d06",icon:"📦",domain:"DevOps",title:"Build ≠ Run",
  quiz:{q:"Dans une chaîne propre, quelle étape produit l’artefact ?",choices:["Build","Run","Monitoring"],answer:0,explain:"Build transforme les sources en artefact. Release associe artefact + configuration. Run exécute la release."},
  mission:{prompt:"Pourquoi éviter de reconstruire différemment juste avant la prod ?",reveal:"Parce qu’on ne déploierait plus exactement l’artefact testé : on perdrait reproductibilité et traçabilité."},
  english:{term:"artifact",q:"En CI/CD, un “artifact” est…",choices:["un résultat construit et versionnable","un utilisateur","une panne DNS"],answer:0,explain:"An artifact is a build output that can be tested, stored and promoted."}},
 {id:"d07",icon:"🛡️",domain:"Cyber",title:"Menace ou vulnérabilité ?",
  quiz:{q:"Un secret API commité publiquement est avant tout…",choices:["une vulnérabilité / exposition","une sauvegarde","un algorithme de chiffrement"],answer:0,explain:"Le secret exposé crée une faiblesse exploitable. Un attaquant qui l’utilise constitue la menace ou l’acteur de menace."},
  mission:{prompt:"Transforme ce cas en chaîne : actif → vulnérabilité → menace → impact.",reveal:"Actif : API/données. Vulnérabilité : secret exposé. Menace : usage non autorisé. Impact : accès, fuite, coût ou altération."},
  english:{term:"exposure",q:"“Credential exposure” veut dire…",choices:["exposition d’identifiants","rotation de logs","segmentation réseau"],answer:0,explain:"Credential exposure means authentication material became accessible to parties that should not have it."}},
 {id:"d08",icon:"☁️",domain:"Cloud",title:"Secret ou config ?",
  quiz:{q:"La région cloud eu-west-3 est généralement…",choices:["une configuration non sensible","un mot de passe","une clé privée"],answer:0,explain:"Une configuration peut être externe au code sans être secrète. Les credentials, eux, doivent être protégés."},
  mission:{prompt:"Classe mentalement : URL API, mot de passe DB, feature flag, clé privée.",reveal:"URL API et feature flag : configuration. Mot de passe DB et clé privée : secrets."},
  english:{term:"secret rotation",q:"“Rotate a secret” signifie…",choices:["remplacer périodiquement le secret et invalider l’ancien","le déplacer dans un autre fichier","le compresser"],answer:0,explain:"Secret rotation replaces credentials on a controlled schedule or after exposure."}},
 {id:"d09",icon:"🧪",domain:"Tests",title:"Le test qui ment",
  quiz:{q:"Un test passe mais vérifie l’ancien titre d’interface. Que risque-t-il ?",choices:["Un faux rouge ou un faux vert","D’améliorer le réseau","De chiffrer le disque"],answer:0,explain:"Un test doit vérifier le comportement attendu actuel, sinon il devient lui-même une source de bruit."},
  mission:{prompt:"Cite la différence entre bug produit et bug de test.",reveal:"Bug produit : le comportement utilisateur est faux. Bug de test : l’application peut être correcte mais l’assertion ou le scénario de test est incorrect."},
  english:{term:"false positive",q:"En test, un “false positive” est…",choices:["une alerte alors que le produit est correct","un succès réel","une mise en production"],answer:0,explain:"A false positive reports a problem that is not actually present."}},
 {id:"d10",icon:"🌍",domain:"Web",title:"Objet ou JSON ?",
  quiz:{q:"JSON.stringify(obj) produit principalement…",choices:["une chaîne JSON","un nouveau serveur","une adresse IP"],answer:0,explain:"JSON.stringify sérialise une valeur JavaScript en texte JSON."},
  mission:{prompt:"Explique en une phrase pourquoi une API utilise souvent JSON.",reveal:"JSON fournit un format texte structuré, portable et facilement sérialisable entre systèmes."},
  english:{term:"serialization",q:"“Serialization” correspond à…",choices:["transformer une structure en format transportable","ouvrir un port réseau","authentifier un utilisateur"],answer:0,explain:"Serialization converts structured data into a representation that can be stored or transmitted."}},
 {id:"d11",icon:"🚪",domain:"Réseau",title:"La gateway",
  quiz:{q:"Quand un hôte utilise-t-il sa gateway par défaut ?",choices:["Quand la destination n’est pas sur un réseau directement joignable","Pour lire un fichier local","Pour calculer un hash"],answer:0,explain:"La route par défaut sert de next hop lorsqu’aucune route plus spécifique ne correspond."},
  mission:{prompt:"Dessine mentalement : PC → ? → Internet. Que mets-tu au milieu ?",reveal:"La passerelle / default gateway, généralement le routeur du réseau local."},
  english:{term:"next hop",q:"“Next hop” désigne…",choices:["le prochain équipement vers lequel le paquet est envoyé","le dernier mot de passe","la prochaine version de Python"],answer:0,explain:"The next hop is the next router or gateway used to move a packet toward its destination."}},
 {id:"d12",icon:"🧠",domain:"IA",title:"Peut-on faire confiance au prompt ?",
  quiz:{q:"Un texte récupéré depuis une source externe par un système RAG doit être traité comme…",choices:["des données potentiellement non fiables","une instruction système de confiance","une clé secrète"],answer:0,explain:"Le contenu récupéré doit rester de la donnée. Il ne doit pas pouvoir redéfinir les règles de sécurité du système."},
  mission:{prompt:"En une phrase, comment limiter l’effet d’une prompt injection ?",reveal:"Séparer clairement données et instructions, contrôler les outils/actions hors modèle et appliquer les autorisations côté système."},
  english:{term:"untrusted input",q:"“Untrusted input” signifie…",choices:["entrée non fiable à valider/encadrer","donnée automatiquement sûre","résultat déjà authentifié"],answer:0,explain:"Untrusted input is data that must not be assumed safe or authoritative."}},
 {id:"d13",icon:"🔎",domain:"Pentest",title:"Recon avant action",
  quiz:{q:"Dans un pentest autorisé, pourquoi commencer par la reconnaissance ?",choices:["Pour comprendre la surface et éviter les actions aveugles","Pour supprimer les logs","Pour contourner le scope"],answer:0,explain:"La reconnaissance construit une carte des actifs, services et versions dans le périmètre autorisé."},
  mission:{prompt:"Cite trois éléments qu’une phase de recon peut inventorier.",reveal:"Par exemple : domaines/sous-domaines, ports ouverts, services, versions, technologies et endpoints exposés."},
  english:{term:"attack surface",q:"“Attack surface” correspond à…",choices:["l’ensemble des points potentiellement exposés","un seul mot de passe","le disque dur"],answer:0,explain:"The attack surface is the set of reachable components and interfaces that could be targeted."}},
 {id:"d14",icon:"🏁",domain:"Portfolio",title:"Raconte ton bug",
  quiz:{q:"En entretien, quel ordre rend un incident technique le plus crédible ?",choices:["Symptôme → diagnostic → cause → fix → tests → vérification","Fix → hasard → symptôme","Technologie → buzzwords → fin"],answer:0,explain:"Un récit d’ingénierie montre comment tu as observé, raisonné, corrigé et prouvé le résultat."},
  mission:{prompt:"Choisis un ancien bug Race Control et raconte uniquement le symptôme puis la cause racine.",reveal:"Le but est de séparer ce que l’utilisateur observait de ce qui cassait réellement dans le code ou l’état."},
  english:{term:"root cause",q:"“Root cause” signifie…",choices:["cause racine","solution temporaire","effet visuel"],answer:0,explain:"The root cause is the underlying reason the failure occurred."}}
];
