const RC_SECTIONS=[
{id:"fundamentals",label:"Fondamentaux IT",icon:"🧱",order:1,goal:"Comprendre OS, Web et logique avant de sécuriser."},
{id:"linux",label:"Linux",icon:"🐧",order:2,goal:"Être autonome au terminal et raisonner permissions/processus."},
{id:"network",label:"Réseau",icon:"🌐",order:3,goal:"Comprendre IP, DNS, routage et protocoles."},
{id:"security",label:"Cybersécurité",icon:"🛡️",order:4,goal:"Maîtriser risque, identité, crypto et vulnérabilités."},
{id:"cloud",label:"Cloud",icon:"☁️",order:5,goal:"Sécuriser IAM, réseau et ressources cloud."},
{id:"devsecops",label:"DevSecOps",icon:"♾️",order:6,goal:"Sécuriser le cycle logiciel et la supply chain."},
{id:"pentest",label:"Pentest",icon:"🔴",order:7,goal:"Raisonner recon → énumération → preuve → remédiation."},
{id:"ai",label:"Sécurité IA",icon:"🤖",order:8,goal:"Sécuriser LLM, RAG, MLOps et gouvernance."},
{id:"portfolio",label:"Portfolio",icon:"🧪",order:9,goal:"Transformer les projets en preuves d'ingénierie."}
];
const RC_TOPICS=[
["fundamentals","os-role","Rôle d'un système d'exploitation",5,"CPU, mémoire, processus, fichiers, noyau et espace utilisateur.","OS,kernel,processus"],
["fundamentals","web-stack","HTTP, HTML, CSS, JavaScript",5,"Comprendre ce qui se passe entre URL, navigateur, serveur, TLS et application.","HTTP,web,TLS"],
["fundamentals","programming","Variables, conditions, boucles, fonctions",4,"Lire et écrire une logique simple en Bash/Python/JavaScript.","code,Python,Bash"],
["fundamentals","formats","JSON, YAML et sérialisation",4,"Lire une configuration, repérer types, structures et erreurs de format.","JSON,YAML,config"],
["linux","linux-fs","Filesystem et navigation",5,"Comprendre /etc, /var, /home, chemins, find, grep et permissions.","filesystem,CLI,find"],
["linux","linux-perms","Permissions, propriétaires et sudo",5,"Maîtriser rwx, chmod, chown, groupes et moindre privilège.","chmod,sudo,least privilege"],
["linux","linux-process","Processus, services et logs",5,"Diagnostiquer avec ps, systemctl, journalctl et signaux.","systemd,logs,processus"],
["linux","linux-net","Réseau sous Linux",5,"Lire interfaces, sockets, routes et DNS depuis le terminal.","ip,ss,route"],
["linux","linux-bash","Bash et environnement",4,"Automatiser proprement et comprendre PATH, exit codes et variables.","Bash,PATH,automation"],
["network","osi","Modèles OSI et TCP/IP",5,"Savoir placer Ethernet, IP, TCP/UDP, TLS, HTTP et DNS.","OSI,TCP/IP,couches"],
["network","ipv4","IPv4, CIDR et sous-réseaux",5,"Calculer réseau, masque, plage hôtes et broadcast.","IPv4,CIDR,subnet"],
["network","routing","Routage et passerelle par défaut",5,"Comprendre next hop, table de routage et route la plus spécifique.","routing,gateway,route"],
["network","dns","DNS",5,"Comprendre résolution, enregistrements A/AAAA/CNAME/MX/NS et cache.","DNS,dig,resolution"],
["network","dhcp","DHCP",4,"Comprendre attribution dynamique, bail, gateway et DNS.","DHCP,lease,LAN"],
["network","http-tls","HTTP/S et TLS",5,"Comprendre méthodes, statuts, headers, certificats et chiffrement en transit.","HTTP,TLS,certificat"],
["security","cia-risk","CIA, menace, vulnérabilité et risque",5,"Distinguer confidentialité, intégrité, disponibilité, impact et vraisemblance.","CIA,risk,threat"],
["security","iam","IAM, authentification et autorisation",5,"Distinguer identité, authN, authZ, MFA, rôles et moindre privilège.","IAM,MFA,RBAC"],
["security","crypto","Hash, chiffrement et signature",5,"Savoir quand utiliser hash, chiffrement symétrique/asymétrique et signature.","crypto,hash,AES"],
["security","vuln","CVE, CVSS et gestion des vulnérabilités",5,"Qualifier une vulnérabilité, son exposition et sa priorité réelle.","CVE,CVSS,patching"],
["security","hardening","Durcissement, logs et détection",5,"Réduire surface d'attaque puis rendre les événements observables.","hardening,logging,detection"],
["security","zerotrust","Zero Trust et segmentation",4,"Ne jamais faire confiance par défaut, vérifier explicitement et limiter le blast radius.","Zero Trust,segmentation,least privilege"],
["cloud","shared","Responsabilité partagée",5,"Savoir ce que sécurise le fournisseur et ce qui reste à la charge du client.","cloud,shared responsibility"],
["cloud","cloud-iam","IAM Cloud",5,"Utilisateurs, rôles, policies, comptes de service et permissions minimales.","IAM,cloud,policy"],
["cloud","vpc","VPC, subnets, security groups",5,"Comprendre segmentation réseau, routes, ACL et exposition publique.","VPC,subnet,firewall"],
["cloud","secrets","Secrets, chiffrement et stockage",5,"Ne pas mettre de secrets dans le code et contrôler accès, rotation et chiffrement.","secrets,KMS,storage"],
["devsecops","git","Git et stratégie de branches",5,"Comprendre commit, SHA, diff, PR, merge, rebase et rollback.","Git,SHA,PR"],
["devsecops","cicd","CI/CD et quality gates",5,"Automatiser build, tests, scans et promotion avec preuves reproductibles.","CI/CD,pipeline,gates"],
["devsecops","docker","Docker et images",5,"Comprendre image, couche, conteneur, registre et durcissement.","Docker,image,container"],
["devsecops","k8s","Kubernetes fondamentaux",4,"Comprendre Pod, Deployment, Service, ConfigMap, Secret et RBAC.","Kubernetes,Pod,RBAC"],
["devsecops","iac","Infrastructure as Code",4,"Décrire l'infrastructure, versionner les changements et contrôler le drift.","IaC,Terraform,drift"],
["devsecops","supply","SAST, DAST, SCA, SBOM et supply chain",5,"Savoir ce que chaque contrôle détecte et où l'insérer dans la pipeline.","SAST,DAST,SCA,SBOM"],
["pentest","method","Méthodologie, scope et preuve",5,"Un pentest est autorisé, borné, reproductible et documenté.","scope,methodology,report"],
["pentest","recon","Reconnaissance et énumération",5,"Cartographier actifs, DNS, ports, services et versions avant toute exploitation.","recon,Nmap,enumeration"],
["pentest","web","Web : injection, XSS, auth et sessions",5,"Comprendre familles de failles web et contrôles côté serveur.","web,XSS,injection"],
["pentest","privesc","Privilege escalation et reporting",4,"Chercher chemins d'élévation dans le scope puis expliquer cause racine et remédiation.","privesc,sudo,report"],
["ai","prompt","Prompt injection",5,"Traiter contenu externe comme donnée non fiable et protéger les actions sensibles hors modèle.","LLM,prompt injection,policy"],
["ai","rag","RAG, ACL et données non fiables",5,"Filtrer les documents selon les droits et séparer données récupérées des instructions système.","RAG,ACL,data security"],
["ai","mlops","MLOps, provenance et gouvernance",4,"Versionner modèles/données, évaluer les risques et contrôler la promotion.","MLOps,governance,provenance"],
["portfolio","race-arch","Race Control : architecture",5,"Expliquer navigateur, moteur déterministe, relais cloud et fournisseurs externes.","Race Control,architecture"],
["portfolio","race-privacy","Race Control : privacy by design",5,"Montrer minimisation des données, frontières de confiance et stockage local.","privacy,data minimization"],
["portfolio","race-tests","Race Control : tests et contre-tests",5,"Expliquer unitaires, E2E, Chromium/WebKit, mutations et invariants métier.","testing,WebKit,mutation"],
["portfolio","race-cicd","Race Control : CI/CD et revue par SHA",5,"Montrer qu'une approbation porte sur un SHA précis et qu'un nouveau commit impose une nouvelle revue.","CI/CD,SHA,review"]
].map(function(x){return{section:x[0],id:x[1],title:x[2],p:x[3],summary:x[4],tags:x[5].split(",")};});
const RC_SOURCES=["Linux Basics for Hackers","Networking Basics","DevOps Pre-Requisites","CompTIA Security+ Guide","API Security in Action","Programme Jedha Cyber","Race Control expliqué de zéro à DevSecOps"];